services:
  api-service:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: order-api
    ports:
      - "5000:5000"
    env_file:
      - ./Docker/server.env
    networks:
      - order-network

  client-app:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: order-client
    ports:
      - "5173:80"
    depends_on:
      - api-service
    env_file:
      - ./Docker/client.env
    networks:
      - order-network

networks:
  order-network:
    driver: bridge
